apiVersion: v1
kind: ConfigMap
metadata:
  name: kpi-config
  namespace: kpi-system
data:
  config.yaml: |
    app:
      name: KPI Management System
      environment: production
      debug: false
      api_prefix: /api
      allowed_hosts:
        - api.kpi-system.com
      cors_origins:
        - https://kpi-system.com
    
    logging:
      level: INFO
      format: json
      retention_days: 30
      max_size_mb: 100
      backup_count: 5
    
    monitoring:
      enabled: true
      prometheus_enabled: true
      slow_request_threshold_ms: 500
      slow_query_threshold_ms: 1000
    
    security:
      password_min_length: 12
      password_require_uppercase: true
      password_require_lowercase: true
      password_require_numbers: true
      password_require_special: true
      session_timeout_minutes: 30
      max_login_attempts: 5
      lockout_duration_minutes: 15
      mfa_enabled: true
      api_rate_limit: 100
      analytics_rate_limit: 1000
    
    cache:
      enabled: true
      default_ttl: 300
      max_size_mb: 1024
      eviction_policy: lru
