server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  
  persistentVolume:
    size: 50Gi
  
  retention: 15d
  
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  
  extraScrapeConfigs: |
    - job_name: 'kpi-backend'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - kpi-system
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
  
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack'
        routes:
        - match:
            severity: critical
          receiver: 'slack'
      receivers:
      - name: 'slack'
        slack_configs:
        - api_url: '${SLACK_WEBHOOK_URL}'
          channel: '#alerts'
          send_resolved: true
  
  rules:
    groups:
    - name: kpi-alerts
      rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 10% for 5 minutes
      
      - alert: HighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          description: Average latency is above 500ms for 5 minutes
      
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container="kpi-backend"} > 900000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Container memory usage is above 900MB
      
      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container="kpi-backend"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: Container CPU usage is above 80%
